<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>3.1 Deliverable: MVC Read Data | <?php echo $page_title; ?></title>
    		
    <link rel="stylesheet" href="../stylesheets/normalize.css" />
	<link rel="stylesheet" href="../stylesheets/main.css" />
	<link rel="stylesheet" href="../stylesheets/custom.css" />

</head>

<body>
    <h1>3.1 Deliverable: MVC Read Data</h1>
    <hr />
    <h3><?php echo $page_title; ?></h3>
    <p><?php echo $content; ?></p>
</body>
</html>